# Generated by Django 5.2.3 on 2025-06-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='roll_no',
            new_name='roll',
        ),
    ]
