# Generated by Django 5.2.3 on 2025-06-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_students_address_students_dob_students_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marks',
            name='total_marks',
        ),
    ]
